# Generated by Django 2.1.5 on 2020-10-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupConstraints',
            new_name='GroupConstraint',
        ),
        migrations.RenameModel(
            old_name='OtherConstraints',
            new_name='OtherConstraint',
        ),
    ]
