# Generated by Django 2.1.5 on 2020-11-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201022_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupConstraint',
            new_name='GroupConstraints',
        ),
        migrations.RenameModel(
            old_name='OtherConstraint',
            new_name='OtherConstraints',
        ),
    ]
