# Generated by Django 2.1.5 on 2020-11-03 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201101_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='studentBreakRequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakPair', to=settings.AUTH_USER_MODEL),
        ),
    ]
