# Generated by Django 2.2 on 2020-11-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201108_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupconstraints',
            options={'ordering': ['theoryGroup', 'labGroup']},
        ),
        migrations.AlterModelOptions(
            name='labgroup',
            options={'ordering': ['groupName']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='theorygroup',
            options={'ordering': ['groupName']},
        ),
    ]
