# Generated by Django 2.2.5 on 2020-11-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201108_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupconstraints',
            options={'ordering': ['labGroup', 'theoryGroup']},
        ),
        migrations.RenameField(
            model_name='pair',
            old_name='student1_id',
            new_name='student1',
        ),
        migrations.RenameField(
            model_name='pair',
            old_name='student2_id',
            new_name='student2',
        ),
    ]
