# Generated by Django 2.2.5 on 2020-11-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201108_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pair',
            options={'ordering': ['student1', 'student2']},
        ),
    ]
